import type {
  Vehicle,
  VehicleImage,
  VehicleGalleryImage,
  VehicleStatus,
} from "@/data/vehicles/vehicle.types";
import { STATUS_TONE } from "@/data/vehicles/vehicle.types";
import { BRAND_MARK } from "./assets";

function vehicleStatusTone(status: VehicleStatus) {
  return STATUS_TONE[status];
}

const vehicleImage = (objectKey: string, altText: string, primary = false): VehicleImage =>
  ({
    id: objectKey,
    vehicleId: "",
    objectKey,
    publicUrl: objectKey,
    altText,
    sortOrder: primary ? 0 : 1,
    isPrimary: primary,
    createdAt: "2025-01-01T00:00:00Z",
  }) as VehicleImage;

const gallery = (image: string, label: string): VehicleGalleryImage[] => [
  { src: image, label },
];

export const mockVehicles: Vehicle[] = [
  {
    id: "zc-harrier-019",
    stockNo: "ZC-0194",
    make: "Toyota",
    model: "Harrier",
    variant: "Premium Advanced",
    year: 2019,
    price: 3865000,
    mileage: 80000,
    engine: "2.0L",
    fuel: "Petrol",
    transmission: "Automatic",
    body: "SUV",
    location: "Lavington, Nairobi",
    status: "available",
    statusTone: vehicleStatusTone("available"),
    color: "Pearl white",
    image: BRAND_MARK,
    gallery: [
      { src: BRAND_MARK, label: "Front three-quarter" },
      { src: BRAND_MARK, label: "Side profile" },
      { src: BRAND_MARK, label: "Rear three-quarter" },
      { src: BRAND_MARK, label: "Cabin detail" },
    ],
    description:
      "The Toyota Harrier is a mid-size crossover SUV built on the TNGA GA-K platform, known in export markets as the Lexus RX from 1998 to 2013. Named after the eastern marsh harrier, this 2019 model pairs a 2.0L turbocharged engine with an AWD system and carries Toyota Safety Sense P. This specific unit is duty-paid, verified with a 108-point condition check, and ready for a showroom walk-through in Lavington.",
    features: [
      "Panoramic sunroof",
      "Leather seats",
      "360 camera",
      "Apple CarPlay",
    ],
    verification: [
      "Duty paid and verified",
      "108-point condition check",
      "Japan auction sheet on file",
      "Price includes registration",
    ],
    specs: {
      Drive: "AWD",
      Seats: "5",
      Doors: "5",
      Power: "170 hp",
      Torque: "180 Nm",
      Consumption: "14 km/l",
      Colour: "Pearl white",
      Registration: "KDG · 2019",
    },
    updated: "12 min ago",
    seller: "Amina Wanjiku",
    segment: "Executive SUV",
    rating: 5,
    featured: true,
    published: true,
    monthly: 78500,
    images: [vehicleImage(BRAND_MARK, "Front three-quarter", true)],
  },
  {
    id: "zc-rav4-020",
    stockNo: "ZC-0201",
    make: "Toyota",
    model: "RAV4",
    variant: "Adventure",
    year: 2020,
    price: 4520000,
    mileage: 63800,
    engine: "2.0L",
    fuel: "Petrol",
    transmission: "CVT",
    body: "SUV",
    location: "Westlands, Nairobi",
    status: "duty_paid",
    statusTone: vehicleStatusTone("duty_paid"),
    color: "Graphite grey",
    image: BRAND_MARK,
    gallery: [
      { src: BRAND_MARK, label: "Front three-quarter" },
      { src: BRAND_MARK, label: "Side profile" },
      { src: BRAND_MARK, label: "Rear three-quarter" },
      { src: BRAND_MARK, label: "Cabin detail" },
    ],
    description:
      "A practical, high-clearance RAV4 with clean lines, strong resale appeal, and a spec that suits both school runs and weekend escapes out of town.",
    features: [
      "Adaptive cruise",
      "Reverse camera",
      "Roof rails",
      "LED headlights",
    ],
    verification: [
      "Duty status recorded",
      "Independent inspection welcome",
      "Price includes registration",
    ],
    specs: {
      Drive: "AWD",
      Seats: "5",
      Doors: "5",
      Power: "170 hp",
      Torque: "210 Nm",
      Consumption: "14 km/l",
      Colour: "Graphite grey",
      Registration: "KDG · 2020",
    },
    updated: "3 hrs ago",
    seller: "Brian Kilonzo",
    segment: "Everyday SUV",
    rating: 4,
    featured: false,
    published: true,
    monthly: 91800,
    images: [vehicleImage(BRAND_MARK, "Front three-quarter", true)],
  },
  {
    id: "zc-forester-021",
    stockNo: "ZC-0218",
    make: "Subaru",
    model: "Forester",
    variant: "EyeSight Turbo",
    year: 2018,
    price: 3245000,
    mileage: 71000,
    engine: "2.0L Turbo",
    fuel: "Petrol",
    transmission: "Automatic",
    body: "SUV",
    location: "Kilimani, Nairobi",
    status: "available",
    statusTone: vehicleStatusTone("available"),
    color: "Crystal black",
    image: BRAND_MARK,
    gallery: [
      { src: BRAND_MARK, label: "Front three-quarter" },
      { src: BRAND_MARK, label: "Side profile" },
      { src: BRAND_MARK, label: "Rear three-quarter" },
      { src: BRAND_MARK, label: "Cabin detail" },
    ],
    description:
      "The Subaru Forester is a compact crossover SUV with a symmetrical all-wheel-drive system and boxer engine that gives it a low center of gravity. Launched in 1997 and now in its fifth generation on the Subaru Global Platform, it features EyeSight driver assist and X-Mode for off-road confidence. This unit combines elevated driving position with practical, everyday usability for Kenyan roads.",
    features: [
      "EyeSight safety",
      "Reverse camera",
      "Heated seats",
      "Roof rails",
    ],
    verification: [
      "Japan auction sheet on file",
      "Full service history",
      "Accident-free",
    ],
    specs: {
      Drive: "AWD",
      Seats: "5",
      Doors: "5",
      Power: "250 hp",
      Torque: "258 lb-ft",
      Consumption: "11 km/l",
      Colour: "Crystal black",
      Registration: "KDG · 2018",
    },
    updated: "5 hrs ago",
    seller: "Sheila Njeri",
    segment: "Adventure SUV",
    rating: 4,
    featured: false,
    published: true,
    monthly: 65900,
    images: [vehicleImage(BRAND_MARK, "Front three-quarter", true)],
  },
  {
    id: "zc-cx5-022",
    stockNo: "ZC-0227",
    make: "Mazda",
    model: "CX-5",
    variant: "XD L Package",
    year: 2018,
    price: 2780000,
    mileage: 76000,
    engine: "2.2L",
    fuel: "Diesel",
    transmission: "Manual",
    body: "SUV",
    location: "Riverside, Nairobi",
    status: "clearing",
    statusTone: vehicleStatusTone("clearing"),
    color: "Soul red crystal",
    image: BRAND_MARK,
    gallery: [
      { src: BRAND_MARK, label: "Front three-quarter" },
      { src: BRAND_MARK, label: "Side profile" },
      { src: BRAND_MARK, label: "Rear three-quarter" },
      { src: BRAND_MARK, label: "Cabin detail" },
    ],
    description:
      "A well-specced diesel CX-5 in the final clearing stage. Reserve now and our team will keep the paperwork moving while you plan your viewing.",
    features: [
      "Leather seats",
      "Bose sound",
      "Blind spot monitor",
      "Power tailgate",
    ],
    verification: [
      "Duty status recorded",
      "Independent inspection welcome",
      "Price includes registration",
    ],
    specs: {
      Drive: "FR",
      Seats: "5",
      Doors: "5",
      Power: "170 hp",
      Torque: "210 Nm",
      Consumption: "14 km/l",
      Colour: "Soul red crystal",
      Registration: "KDG · 2018",
    },
    updated: "2 days ago",
    seller: "Moses Njoroge",
    segment: "Diesel SUV",
    rating: 4,
    featured: false,
    published: true,
    monthly: 56500,
    images: [vehicleImage(BRAND_MARK, "Front three-quarter", true)],
  },
  {
    id: "zc-hilux-023",
    stockNo: "ZC-0234",
    make: "Toyota",
    model: "Hilux",
    variant: "Double Cab Legend",
    year: 2021,
    price: 5680000,
    mileage: 42000,
    engine: "2.8L",
    fuel: "Diesel",
    transmission: "Automatic",
    body: "Pickup",
    location: "Mombasa Road, Nairobi",
    status: "in_transit",
    statusTone: vehicleStatusTone("in_transit"),
    color: "Arctic white",
    image: BRAND_MARK,
    gallery: [
      { src: BRAND_MARK, label: "Front three-quarter" },
      { src: BRAND_MARK, label: "Side profile" },
      { src: BRAND_MARK, label: "Rear three-quarter" },
      { src: BRAND_MARK, label: "Cabin detail" },
    ],
    description:
      "A low-mileage double cab for teams that need a dependable work partner with serious road presence. Arrival is tracked daily from Mombasa Road.",
    features: [
      "4WD low range",
      "Tow bar",
      "Reverse camera",
      "Alloy rims",
    ],
    verification: [
      "Duty status recorded",
      "Independent inspection welcome",
      "Price includes registration",
    ],
    specs: {
      Drive: "4WD",
      Seats: "5",
      Doors: "4",
      Power: "170 hp",
      Torque: "330 lb-ft",
      Consumption: "12 km/l",
      Colour: "Arctic white",
      Registration: "KDG · 2021",
    },
    updated: "Just now",
    seller: "Moses Njoroge",
    segment: "Workhorse pickup",
    rating: 5,
    featured: false,
    published: true,
    monthly: 115400,
    images: [vehicleImage(BRAND_MARK, "Front three-quarter", true)],
  },
  {
    id: "zc-axio-024",
    stockNo: "ZC-0240",
    make: "Toyota",
    model: "Corolla Axio",
    variant: "Hybrid G",
    year: 2019,
    price: 1895000,
    mileage: 68000,
    engine: "1.5L",
    fuel: "Hybrid",
    transmission: "CVT",
    body: "Sedan",
    location: "Parklands, Nairobi",
    status: "reserved",
    statusTone: vehicleStatusTone("reserved"),
    color: "Silver metallic",
    image: BRAND_MARK,
    gallery: [
      { src: BRAND_MARK, label: "Front three-quarter" },
      { src: BRAND_MARK, label: "Side profile" },
      { src: BRAND_MARK, label: "Rear three-quarter" },
      { src: BRAND_MARK, label: "Cabin detail" },
    ],
    description:
      "A compact hybrid sedan with city-friendly running costs and a clean, easy-to-own profile. Currently held for a buyer pending paperwork.",
    features: [
      "Hybrid drive",
      "Push start",
      "Reverse camera",
      "Keyless entry",
    ],
    verification: [
      "Duty status recorded",
      "Independent inspection welcome",
      "Price includes registration",
    ],
    specs: {
      Drive: "FWD",
      Seats: "5",
      Doors: "4",
      Power: "100 hp",
      Torque: "110 lb-ft",
      Consumption: "25 km/l",
      Colour: "Silver metallic",
      Registration: "KDG · 2019",
    },
    updated: "1 day ago",
    seller: "Lilian Karanja",
    segment: "City hybrid",
    rating: 4,
    featured: false,
    published: true,
    monthly: 38500,
    images: [vehicleImage(BRAND_MARK, "Front three-quarter", true)],
  },
];

export const leads = [
  {
    id: "LD-1048",
    name: "Mercy Wanjiku",
    vehicle: "Toyota Harrier 2019",
    source: "WhatsApp",
    status: "New",
    time: "8 min ago",
    initials: "MW",
  },
  {
    id: "LD-1047",
    name: "Daniel Otieno",
    vehicle: "Subaru Forester XT",
    source: "Website enquiry",
    status: "Contacted",
    time: "42 min ago",
    initials: "DO",
  },
  {
    id: "LD-1046",
    name: "Sheila Njeri",
    vehicle: "Mazda CX-5",
    source: "WhatsApp",
    status: "Reserved",
    time: "2 hrs ago",
    initials: "SN",
  },
  {
    id: "LD-1045",
    name: "Mark Kiplagat",
    vehicle: "Toyota RAV4",
    source: "Finance match",
    status: "New",
    time: "3 hrs ago",
    initials: "MK",
  },
];

export const reservations = [
  {
    id: "RS-2204",
    vehicle: "Isuzu D-Max 2021",
    buyer: "David M.",
    amount: 10000,
    expires: "31h 18m",
    status: "Active",
  },
  {
    id: "RS-2203",
    vehicle: "Mazda CX-5 2018",
    buyer: "Sheila N.",
    amount: 10000,
    expires: "Converted",
    status: "Converted",
  },
  {
    id: "RS-2202",
    vehicle: "Toyota Harrier 2019",
    buyer: "Patrick K.",
    amount: 10000,
    expires: "Released",
    status: "Released",
  },
];

export const tradeIns = [
  {
    id: "TI-088",
    name: "Agnes W.",
    vehicle: "2014 Toyota Fielder",
    estimate: "KES 1.1M – 1.25M",
    source: "Website",
    status: "New",
    time: "24 min ago",
  },
  {
    id: "TI-087",
    name: "Peter N.",
    vehicle: "2012 Nissan X-Trail",
    estimate: "KES 760K – 900K",
    source: "WhatsApp",
    status: "Reviewing",
    time: "2 hrs ago",
  },
  {
    id: "TI-086",
    name: "Lilian K.",
    vehicle: "2016 Mazda Demio",
    estimate: "KES 980K – 1.1M",
    source: "Website",
    status: "Offer sent",
    time: "Yesterday",
  },
];

export const financeRequests = [
  {
    id: "FM-311",
    name: "Mark Kiplagat",
    employment: "Salaried",
    budget: "KES 90K / month",
    vehicle: "Toyota RAV4",
    partner: "NCBA",
    status: "New",
    time: "3 hrs ago",
  },
  {
    id: "FM-310",
    name: "Esther M.",
    employment: "Business owner",
    budget: "KES 120K / month",
    vehicle: "Subaru Forester",
    partner: "Mogo",
    status: "Matched",
    time: "Yesterday",
  },
  {
    id: "FM-309",
    name: "Joseph O.",
    employment: "Diaspora buyer",
    budget: "KES 150K / month",
    vehicle: "Toyota Harrier",
    partner: "KCB",
    status: "Contacted",
    time: "2 days ago",
  },
];

export const sales = [
  {
    id: "SL-4001",
    agent: "Amina W.",
    vehicle: "Toyota Harrier 2019",
    buyer: "James Mwangi",
    amount: 3865000,
    status: "Completed",
    date: "25 Aug 2026",
  },
  {
    id: "SL-4002",
    agent: "Brian K.",
    vehicle: "Subaru Forester XT",
    buyer: "Lucy Wambui",
    amount: 3245000,
    status: "Completed",
    date: "24 Aug 2026",
  },
  {
    id: "SL-4003",
    agent: "Sheila Njeri",
    vehicle: "Toyota RAV4 2020",
    buyer: "Samuel Otieno",
    amount: 4520000,
    status: "Pending",
    date: "23 Aug 2026",
  },
  {
    id: "SL-4004",
    agent: "Amina W.",
    vehicle: "Toyota Corolla Axio",
    buyer: "Grace Achieng",
    amount: 1895000,
    status: "Completed",
    date: "22 Aug 2026",
  },
];

export const staff = [
  {
    id: "AG-001",
    name: "Amina Wanjiku",
    role: "Admin",
    branch: "Nairobi",
    status: "Active",
    sales: 24,
    response: "8m",
  },
  {
    id: "AG-002",
    name: "Brian Kilonzo",
    role: "Sales",
    branch: "Nairobi",
    status: "Active",
    sales: 18,
    response: "11m",
  },
  {
    id: "AG-003",
    name: "Moses Njoroge",
    role: "Yard / Ops",
    branch: "Nairobi",
    status: "Active",
    sales: 12,
    response: "15m",
  },
  {
    id: "AG-004",
    name: "Sheila Njeri",
    role: "Sales",
    branch: "Mombasa",
    status: "Active",
    sales: 15,
    response: "7m",
  },
];
