// Liquid Safari reminder: supporting pages should carry the same glass, orbit, Kenyan context, and no-pressure voice as the showroom and dealer cockpit.
import { ArrowRight, BadgeCheck, Banknote, CalendarDays, CarFront, Check, FileCheck2, Globe2, MapPin, MessageCircle, ShieldCheck, Truck } from "lucide-react";
import { Link } from "wouter";
import { PageFrame } from "@/components/SiteChrome";

type ServiceType = "finance" | "trade" | "diaspora" | "about" | "contact" | "legal";
const content: Record<ServiceType, { eyebrow: string; title: string; intro: string; actions: string[]; icon: typeof Banknote }> = {
  finance: { eyebrow: "Finance, without the fog", title: "Make the monthly\nnumber make sense.", intro: "Start with the car, your comfortable monthly range, and the deposit you have in mind. We match the next conversation to Kenyan finance partners and show the assumptions clearly.", actions: ["Choose a car", "See a sample repayment", "Talk to a finance guide"], icon: Banknote },
  trade: { eyebrow: "Trade in / Sell on", title: "Your next car can\nstart with the old one.", intro: "Share the vehicle you have today and our team will help you understand its likely range, paperwork, and the cleanest path into your next Zara Cars unit.", actions: ["Tell us about your car", "Get a range", "Book a handover"], icon: Truck },
  diaspora: { eyebrow: "Diaspora desk", title: "A Nairobi handover,\nwherever you are.", intro: "We help buyers abroad stay close to the details: verified stock, guided video viewings, paperwork updates, and a clear handover plan for family or a driver in Kenya.", actions: ["Browse ready stock", "Request a video viewing", "Ask for a handover plan"], icon: Globe2 },
  about: { eyebrow: "The Zara Cars standard", title: "Less showroom theatre.\nMore useful detail.", intro: "Zara Cars is built around the moments that matter when buying in Kenya: the real price, the condition file, the location, and a person who will answer the follow-up.", actions: ["See live stock", "Meet the dealer team", "Read our trust file"], icon: ShieldCheck },
  contact: { eyebrow: "The Nairobi team", title: "Bring us the\nquestion you have.", intro: "Ask for a walkaround, a second look at the paperwork, or a quiet viewing slot. We are happiest when the next step is clear on both sides.", actions: ["WhatsApp the showroom", "Call +254 700 000 000", "Book a viewing"], icon: MessageCircle },
  legal: { eyebrow: "Trust & verification", title: "Nothing important\nshould stay hidden.", intro: "Our vehicle records make room for the details Kenyan buyers need: duty status, auction sheet, inspection notes, service history, and a price that explains itself.", actions: ["Browse verified stock", "Ask for a condition file", "Talk to the team"], icon: FileCheck2 },
};

export default function ServicePage({ type }: { type: ServiceType }) {
  const page = content[type];
  const Icon = page.icon;
  return <PageFrame><section className="service-hero"><div><p className="section-kicker">{page.eyebrow}</p><h1>{page.title.split("\n").map((line, index) => <span key={line} className={index === 1 ? "red-line" : ""}>{line}<br /></span>)}</h1><p>{page.intro}</p><div className="hero-actions"><Link href={type === "contact" ? "https://wa.me/254700000000" : "/inventory"} className="button button-red">{page.actions[0]} <ArrowRight size={16} /></Link><Link href="/dealer" className="button button-quiet">Open dealer workspace <ArrowRight size={16} /></Link></div></div><div className="service-orbit-card"><span className="service-icon"><Icon size={24} /></span><small>Designed around the next step</small><strong>{page.actions[1]}</strong><p>Clear, local, and ready for a real conversation.</p><div className="service-checks"><span><Check size={14} /> Kenyan context</span><span><Check size={14} /> No pressure language</span><span><Check size={14} /> Human follow-up</span></div></div></section><section className="service-grid"><div><p className="section-kicker">How it works</p><h2>Small steps.<br />Fewer unknowns.</h2></div><div className="service-steps"><div><span>01</span><div><strong>{page.actions[0]}</strong><p>Start with what you know, then let the team fill in the gaps without making you repeat yourself.</p></div><CarFront size={19} /></div><div><span>02</span><div><strong>{page.actions[1]}</strong><p>Get a practical next step based on the actual unit, location, status, and paperwork.</p></div><FileCheck2 size={19} /></div><div><span>03</span><div><strong>{page.actions[2]}</strong><p>Move forward only when the details feel right. A viewing, a call, or a WhatsApp answer is enough.</p></div><CalendarDays size={19} /></div></div></section><section className="service-cta"><div><p className="section-kicker">Ready when you are</p><h2>Good cars deserve<br />clear decisions.</h2></div><Link href="/inventory" className="button button-red">See live stock <ArrowRight size={16} /></Link></section></PageFrame>;
}
