import { createContext, useContext, useState } from "react";

type Language = "en" | "sw";

const translations: Record<Language, Record<string, string>> = {
  en: {
    "nav.home": "Home",
    "nav.inventory": "Browse cars",
    "nav.finance": "Finance",
    "nav.tradeIn": "Trade in",
    "nav.about": "About",
    "nav.contact": "Contact",
    "nav.diaspora": "Diaspora",
    "nav.legal": "Legal & trust",
    "nav.dealer": "Dealer login",
    "cta.browse": "Browse available cars",
    "cta.chat": "Chat",
    "cta.chatHuman": "Chat to a human",
    "cta.reserve": "Reserve with M-Pesa",
    "cta.whatsapp": "WhatsApp",
    "cta.viewing": "Book a viewing",
    "cta.tradeIn": "Get a trade-in estimate",
    "cta.getMatched": "Get matched",
    "cta.sendMessage": "Send message",
    "cta.startDiaspora": "Start diaspora purchase",
    "cta.askWhatsApp": "Ask on WhatsApp",
    "cta.playVideo": "Play",
    "hero.headline": "Know the car. Know the price. Drive with confidence.",
    "hero.subhead":
      "Kenya's most transparent way to buy a car. Verified stock, live status, and one honest drive-away number.",
    "hero.searchPlaceholder": "Search by make or model e.g. Toyota, Harrier",
    "hero.findMyCar": "Find my car",
    "hero.popular": "Popular:",
    "hero.suvs": "SUVs",
    "hero.under3m": "Under KES 3M",
    "hero.hybrid": "Hybrid",
    "hero.readyToView": "Ready to view",
    "footer.tagline":
      "Kenya's most transparent way to buy a car. Nairobi first, nationwide next.",
    "footer.copy": "© 2026 Zara Cars. Transparent by design.",
    "status.inTransit": "In Transit",
    "status.clearing": "Clearing",
    "status.dutyPaid": "Duty Paid",
    "status.readyToView": "Ready to View",
    "status.reserved": "Reserved",
    "status.sold": "Sold",
    "price.driveAway": "Drive-away price",
    "price.orMonthly": "or {amount} / month",
    "price.fromMonthly": "from {amount} / month",
    "price.suggestedDeposit": "{amount} suggested deposit",
    "price.whatsIncluded": "What's included in this price",
    "price.driveAwayTotal": "Drive-away total",
    "label.kmDriven": "km driven",
    "label.engine": "engine",
    "label.gearbox": "gearbox",
    "label.yourName": "Your name",
    "label.phoneNumber": "M-Pesa / WhatsApp number",
    "label.preferredTime": "Preferred time",
    "label.employmentType": "Employment type",
    "label.targetPrice": "Target car price (KES)",
    "label.deposit": "Deposit (KES)",
    "label.term": "Term (months)",
    "label.estimatedMonthly": "Estimated monthly repayment",
    "label.make": "Make",
    "label.model": "Model",
    "label.year": "Year",
    "label.mileage": "Mileage (km)",
    "label.photos": "Photos (front, back, side)",
    "label.message": "Message",
    "label.yourNameContact": "Your name",
    "label.phoneWhatsApp": "Phone or WhatsApp",
    "section.howItWorks": "How it works",
    "section.honestWayIn": "The honest way in",
    "section.trust": "The Zara standard",
    "section.keepLooking": "Keep looking",
    "section.similarCars": "Similar cars",
    "section.stockPipeline": "Stock & pipeline",
    "section.leads": "Lead inbox",
    "section.reservations": "Reservations",
    "section.tradeIns": "Trade-in queue",
    "section.finance": "Finance interest",
    "section.sales": "Sales",
    "section.agents": "Agents",
    "section.sellOnBehalf": "Sell on behalf",
    "section.agentPerformance": "Agent performance",
    "section.activeListings": "Active listings",
    "section.commission": "Commission",
    "section.overview": "Overview",
    "label.agent": "Agent",
    "label.buyer": "Buyer",
    "label.vehicle": "Vehicle",
    "label.amount": "Amount",
    "label.commission": "Commission",
    "label.date": "Date",
    "label.status": "Status",
    "label.role": "Role",
    "label.branch": "Branch",
    "label.totalSales": "Total sales",
    "label.totalValue": "Total value",
    "label.conversionRate": "Conversion rate",
    "label.leadsHandled": "Leads handled",
    "label.avgResponse": "Avg response",
    "label.askingPrice": "Asking price",
    "label.listedDate": "Listed date",
    "label.expiresDate": "Expires date",
    "label.listingFee": "Listing fee",
    "cta.newListing": "New listing",
    "cta.markSold": "Mark as sold",
    "cta.extendListing": "Extend listing",
    "metric.salesThisMonth": "Sales this month",
    "metric.agentCount": "Agent count",
    "metric.commissionPaid": "Commission paid",
    "metric.conversion": "Conversion",
    "metric.activeListings": "Active listings",
    "metric.avgListingValue": "Avg listing value",
    "page.home": "Home",
    "page.inventory": "Inventory",
    "page.financing": "Financing",
    "page.tradeIn": "Trade In",
    "page.about": "About",
    "page.contact": "Contact",
    "page.diaspora": "Diaspora",
    "page.legal": "Legal & Trust",
    "page.vehicleDetail": "Vehicle Detail",
    "page.dealer": "Dealer Dashboard",
    "hero.browseCars": "Browse available cars",
    "hero.bookViewing": "Book a viewing",
    "hero.searchByMake": "Search by make or model e.g. Toyota, Harrier",
    "section.featuredInventory": "Featured inventory",
    "section.threeStep": "Click. Click. Drive.",
    "section.tradeIn": "Trade in your current car",
    "section.conditionReport": "Condition report on file",
    "section.priceBreakdown": "Price breakdown",
    "section.verification": "Verification",
    "section.features": "Features",
    "section.gallery": "Gallery",
    "section.videoWalkaround": "Video walkaround",
    "section.financeMatch": "Finance match",
    "section.partnerNetwork": "Partner network",
    "section.howFinanceWorks": "How it works",
    "section.tradeInEstimate": "Trade-in estimator",
    "section.whyTradeIn": "Why trade in with Zara",
    "section.recentTradeIns": "Recent trade-ins",
    "section.ourStory": "Our story",
    "section.foundingStory": "The founding story",
    "section.verificationProcess": "Verification process",
    "section.values": "Values",
    "section.visitYard": "Visit the yard",
    "section.sendMessage": "Send a message",
    "section.showroom": "Showroom",
    "section.branches": "Branches",
    "section.howDiasporaWorks": "How it works",
    "section.paymentOptions": "Payment options",
    "section.testimonials": "What our diaspora buyers say",
    "section.reservationDeposits": "Reservation deposits",
    "section.refundPolicy": "Refund policy",
    "section.dutyExplainer": "Duty & import explainer",
    "section.buyerProtections": "Buyer protections",
    "section.questions": "Questions?",
    "label.backToHome": "Back to home",
    "label.backToInventory": "Back to inventory",
    "label.liveInventory": "Live inventory",
    "label.findYourNextCar": "Find your next car.",
    "label.driveAwayNumber": "Every number is the drive-away number.",
    "label.searchPlaceholder": "Search by make or model",
    "label.allMakes": "All makes",
    "label.allStatuses": "All statuses",
    "label.allBodyTypes": "All body types",
    "label.clearFilters": "Clear filters",
    "label.show": "Show",
    "label.saveVehicle": "Save vehicle",
    "label.viewDetails": "View details",
    "label.reserveMpesa": "Reserve with M-Pesa",
    "label.chatWhatsApp": "Chat on WhatsApp",
    "label.bookViewing": "Book a viewing",
    "cta.importStock": "Import stock",
    "cta.addVehicle": "Add vehicle",
    "cta.exportLeads": "Export leads",
    "cta.exportReport": "Export report",
    "cta.exportQueue": "Export queue",
    "cta.exportRequests": "Export requests",
    "cta.exportSales": "Export sales",
    "cta.exportAgentReport": "Export report",
    "metric.liveVehicles": "Live vehicles",
    "metric.readyToView": "Ready to view",
    "metric.openLeads": "Open leads",
    "metric.monthlySales": "Monthly sales",
    "metric.activeHolds": "Active holds",
    "metric.convertedMonth": "Converted this month",
    "metric.autoReleased": "Auto-released",
    "metric.newSubmissions": "New submissions",
    "metric.offersSent": "Offers sent",
    "metric.convertedStock": "Converted to stock",
    "metric.newRequests": "New requests",
    "metric.matched": "Matched",
    "metric.partnerPipeline": "Partner pipeline",
    "metric.activeAgents": "Active agents",
    "metric.topPerformer": "Top performer",
    "metric.avgResponse": "Avg response",
    "metric.totalValue": "Total value",
    "metric.commissionRate": "Commission rate",
    "financing.headline": "Buy with confidence, pay over time.",
    "tradeIn.headline": "Upgrade with clarity.",
    "about.headline": "Built for Kenya, not copied from abroad.",
    "contact.headline": "We are one message away.",
    "diaspora.headline": "Buy from abroad. We handle Kenya.",
    "legal.headline": "Transparent by design.",
    "inventory.headline": "Find your next car.",
    "financing.subhead":
      "We match you to the right partner based on how you earn — salaried, business owner, boda/matatu SACCO, or diaspora. No generic calculators, no cold calls.",
    "tradeIn.subhead":
      "Tell us what you drive, add a few photos, and our team will send a provisional range. No pressure, no guesswork.",
    "about.subhead":
      "Zara Cars was founded in Nairobi to fix the one thing the used-car market refuses to solve: trust. We inspect, verify, and price every car as if our own family were buying it.",
    "contact.subhead":
      "Visit the yard, call us, or WhatsApp. No call centres, no automated replies — a real Zara Cars person picks up.",
    "diaspora.subhead":
      "A dedicated flow for Kenyans abroad buying for family at home: pay in USD/EUR, second delivery contact, WhatsApp updates in place of site logins.",
    "legal.subhead":
      "We publish the policies that most dealer sites hide. If you have a question, ask us directly on WhatsApp.",
  },
  sw: {
    "nav.home": "Nyumbani",
    "nav.inventory": "Tafuta gari",
    "nav.finance": "Kifedha",
    "nav.tradeIn": "Badilisha",
    "nav.about": "Kuhusu sisi",
    "nav.contact": "Wasiliana",
    "nav.diaspora": "Diaspora",
    "nav.legal": "Sheria na uaminifu",
    "nav.dealer": "Ingia kama mfanyabiashara",
    "cta.browse": "Tafuta gari zinazopatikana",
    "cta.chat": "Piga mazungumzo",
    "cta.chatHuman": "Zungumza na binadamu",
    "cta.reserve": "Hifadhi kwa M-Pesa",
    "cta.whatsapp": "WhatsApp",
    "cta.viewing": "Panga kutazama",
    "cta.tradeIn": "Pata makadirio ya ubadilishaji",
    "cta.getMatched": "Pata mfanyabiashara",
    "cta.sendMessage": "Tuma ujumbe",
    "cta.startDiaspora": "Anza ununuzi wa diaspora",
    "cta.askWhatsApp": "Uliza kwa WhatsApp",
    "cta.playVideo": "Cheza",
    "hero.headline": "Jua gari. Jua bei. Endelea kwa uhakika.",
    "hero.subhead":
      "Njia ya uwazi zaidi ya kununua gari Kenya. Stock iliyothibitishwa, hali halisi, na bei kamili moja.",
    "hero.searchPlaceholder": "Tafuta kwa au mfano e.g. Toyota, Harrier",
    "hero.findMyCar": "Pata gari langu",
    "hero.popular": "Maarufu:",
    "hero.suvs": "SUVs",
    "hero.under3m": "Chini ya KES 3M",
    "hero.hybrid": "Hybrid",
    "hero.readyToView": "Tayari kutazama",
    "footer.tagline":
      "Njia ya uwazi zaidi ya kununua gari Kenya. Nairobi kwanza, nchi nzima inafuata.",
    "footer.copy": "© 2026 Zara Cars. Uwazi kwa muundo.",
    "status.inTransit": "Nje ya nchi",
    "status.clearing": "Inafanywa usafi",
    "status.dutyPaid": "Ushuru umelipwa",
    "status.readyToView": "Tayari kutazama",
    "status.reserved": "Imehifadhiwa",
    "status.sold": "Imeuzwa",
    "price.driveAway": "Bei ya kwenda",
    "price.orMonthly": "au {amount} / mwezi",
    "price.fromMonthly": "kutoka {amount} / mwezi",
    "price.suggestedDeposit": "{amount} ambao unashauriwa kulipa",
    "price.whatsIncluded": "Nini kimejumuishwa kwenye bei hii",
    "price.driveAwayTotal": "Jumla ya kwenda",
    "label.kmDriven": "km zilizopigwa",
    "label.engine": " Injini",
    "label.gearbox": "Gearbox",
    "label.yourName": "Jina lako",
    "label.phoneNumber": "Namba ya M-Pesa / WhatsApp",
    "label.preferredTime": "Wakati unaopendelea",
    "label.employmentType": "Aina ya ajira",
    "label.targetPrice": "Bei ya lengwa (KES)",
    "label.deposit": "Amana (KES)",
    "label.term": "Muda (miezi)",
    "label.estimatedMonthly": "Marejesho ya kila mwezi yanayokadiriwa",
    "label.make": "Fani",
    "label.model": "Mfano",
    "label.year": "Mwaka",
    "label.mileage": "Urefu (km)",
    "label.photos": "Picha (mbele, nyuma, upande)",
    "label.message": "Ujumbe",
    "label.yourNameContact": "Jina lako",
    "label.phoneWhatsApp": "Simu au WhatsApp",
    "section.howItWorks": "Inavyofanya kazi",
    "section.honestWayIn": "Njia ya kweli",
    "section.trust": "Kiwango cha Zara",
    "section.keepLooking": "Endelea kutafuta",
    "section.similarCars": "Gari zinazofanana",
    "section.stockPipeline": "Stock na mfumo",
    "section.leads": "Kikwazo cha wateja",
    "section.reservations": "Uhifadhi",
    "section.tradeIns": "Mfanyabiashara wa ubadilishaji",
    "section.finance": "Kifedha",
    "section.sales": "Mauzo",
    "section.agents": "Wakala",
    "section.sellOnBehalf": "Uza kwa niaba",
    "section.agentPerformance": "Uwiano wa wakala",
    "section.activeListings": "Milango inayovuta",
    "section.commission": "Kiwango cha usimamizi",
    "section.overview": "Muhtasari",
    "label.agent": "Wakala",
    "label.buyer": "Mnunuzi",
    "label.vehicle": "Gari",
    "label.amount": "Kiasi",
    "label.commission": "Usimamizi",
    "label.date": "Tarehe",
    "label.status": "Hali",
    "label.role": "Wajibu",
    "label.branch": "Tawi",
    "label.totalSales": "Jumla ya mauzo",
    "label.totalValue": "Thamani ya jumla",
    "label.conversionRate": "Kiwango cha ubadilishaji",
    "label.leadsHandled": "Wateja waliosimamiwa",
    "label.avgResponse": "Jibu la wastani",
    "label.askingPrice": "Bei ya kuuza",
    "label.listedDate": "Tarehe ya kuorodha",
    "label.expiresDate": "Tarehe ya kumalizika",
    "label.listingFee": "Ada ya kuorodha",
    "cta.newListing": "Orodha mpya",
    "cta.markSold": "Weka kuwa limeuzwa",
    "cta.extendListing": "Zidisha orodha",
    "metric.salesThisMonth": "Mauzo ya mwezi huu",
    "metric.agentCount": "Idadi ya wakala",
    "metric.commissionPaid": "Usimamizi uliolipwa",
    "metric.conversion": "Ubadilishaji",
    "metric.activeListings": "Milango inayovuta",
    "metric.avgListingValue": "Thamani ya wastani",
    "page.home": "Nyumbani",
    "page.inventory": "Orodha ya gari",
    "page.financing": "Kifedha",
    "page.tradeIn": "Ubadilishaji",
    "page.about": "Kuhusu sisi",
    "page.contact": "Wasiliana",
    "page.diaspora": "Diaspora",
    "page.legal": "Sheria na uaminifu",
    "page.vehicleDetail": "Maelezo ya gari",
    "page.dealer": "Dashibodi ya mfanyabiashara",
    "hero.browseCars": "Tafuta gari zinazopatikana",
    "hero.bookViewing": "Panga kutazama",
    "hero.searchByMake": "Tafuta kwa au mfano e.g. Toyota, Harrier",
    "section.featuredInventory": "Orodha ya gari iliyochaguliwa",
    "section.threeStep": "Bonyeza. Bonyeza. Endelea.",
    "section.tradeIn": "Badilisha gari lako la sasa",
    "section.conditionReport": "Ripoti ya hali ipo",
    "section.priceBreakdown": "Ufafanuzi wa bei",
    "section.verification": "Uthibitisho",
    "section.features": "Sifa",
    "section.gallery": "Maktaba",
    "section.videoWalkaround": "Video ya kutembea",
    "section.financeMatch": "Ulinganuo wa kifedha",
    "section.partnerNetwork": "Mtandao wa washirika",
    "section.howFinanceWorks": "Inavyofanya kazi",
    "section.tradeInEstimate": "Kadirio la ubadilishaji",
    "section.whyTradeIn": "Kwa nini ubadilishaji na Zara",
    "section.recentTradeIns": "Ubadilishaji wa hivi karibuni",
    "section.ourStory": "Hadithi yetu",
    "section.foundingStory": "Hadithi ya kuundwa",
    "section.verificationProcess": "Mchakato wa uthibitisho",
    "section.values": "Maadili",
    "section.visitYard": "Tembelea yadi",
    "section.sendMessage": "Tuma ujumbe",
    "section.showroom": "Yadi ya kuonyesha",
    "section.branches": "Tawi",
    "section.howDiasporaWorks": "Inavyofanya kazi",
    "section.paymentOptions": "Chaguzi za malipo",
    "section.testimonials": "Watu wa diaspora wanachosema",
    "section.reservationDeposits": "Amana ya uhifadhi",
    "section.refundPolicy": "Sera ya kurejesha",
    "section.dutyExplainer": "Kuelewa kwa ushuru na uingizaji",
    "section.buyerProtections": "Ulinzi wa mnunuzi",
    "section.questions": "Maswali?",
    "label.backToHome": "Rudi nyumbani",
    "label.backToInventory": "Rudi kwenye orodha",
    "label.liveInventory": "Orodha ya gari inayovuta",
    "label.findYourNextCar": "Pata gari lako lijalo.",
    "label.driveAwayNumber": "Kila namba ni namba ya kwenda.",
    "label.searchPlaceholder": "Tafuta kwa au mfano",
    "label.allMakes": "Fani zote",
    "label.allStatuses": "Hali zote",
    "label.allBodyTypes": "Aina zote",
    "label.clearFilters": "Futa vichujio",
    "label.show": "Onyesha",
    "label.saveVehicle": "Hifadhi gari",
    "label.viewDetails": "Onyesha maelezo",
    "label.reserveMpesa": "Hifadhi kwa M-Pesa",
    "label.chatWhatsApp": "Zungumza kwa WhatsApp",
    "label.bookViewing": "Panga kutazama",
    "cta.importStock": "Ingiza stock",
    "cta.addVehicle": "Ongeza gari",
    "cta.exportLeads": "Hamisha wateja",
    "cta.exportReport": "Hamisha ripoti",
    "cta.exportQueue": "Hamisha mfanyabiashara",
    "cta.exportRequests": "Hamisha maombi",
    "cta.exportSales": "Hamisha mauzo",
    "cta.exportAgentReport": "Hamisha ripoti",
    "metric.liveVehicles": "Gari zinazovuta",
    "metric.readyToView": "Tayari kutazama",
    "metric.openLeads": "Wateja wapya",
    "metric.monthlySales": "Mauzo ya mwezi",
    "metric.activeHolds": "Uhifadhi unaovuta",
    "metric.convertedMonth": "Ubadilishaji wa mwezi huu",
    "metric.autoReleased": "Ulimwengu wa kujitolea",
    "metric.newSubmissions": "Maombi mapya",
    "metric.offersSent": "Ofa zilizotumwa",
    "metric.convertedStock": "Ilibadilishwa kuwa stock",
    "metric.newRequests": "Maombi mapya",
    "metric.matched": "Yanayofaa",
    "metric.partnerPipeline": "Mfumo wa washirika",
    "metric.activeAgents": "Wakala wanaoendeshwa",
    "metric.topPerformer": "Mwenye kujifunza zaidi",
    "metric.avgResponse": "Jibu la wastani",
    "metric.totalValue": "Thamani ya jumla",
    "metric.commissionRate": "Kiwango cha usimamizi",
    "financing.headline": "Jua gari. Jua bei. Endelea kwa uhakika.",
    "tradeIn.headline": "Badilisha kwa uwazi.",
    "about.headline": "Imeundwa kwa Kenya, sio kunakiliwa kutoka nje.",
    "contact.headline": "Tuko moja kwa ujumbe.",
    "diaspora.headline": "Ununue kutoka nje. Tunashughulikia Kenya.",
    "legal.headline": "Uwazi kwa muundo.",
    "inventory.headline": "Pata gari lako lijalo.",
    "financing.subhead":
      "Tunakufananisha na mfanyabiashara wa haki kulingana na jinsi unavyopata kipato — mfanyabiashara, mwenye biashara, SACCO ya boda/matatu, au diaspora. Hakuna kalkuleta za kawaida, hakuna simu za baridi.",
    "tradeIn.subhead":
      "Tuambie gari unalolowesha, ongeza picha chache, na timu yetu itakutumia kipimo cha muda. Hakuna shinikizo, hakuna kudhihirisha.",
    "about.subhead":
      "Zara Cars ilianzishwa Nairobi kutatua kitu kimoja ambacho soko la gari la zamani hukataa kutatua: uaminifu. Tunaangalia, kuthibitisha, na kupisha gari kila mmoja kama familia yetu inavyonunua.",
    "contact.subhead":
      "Tembelea yadi, sutua, au WhatsApp. Hakuna vituo vya simu, hakuna majibu ya kiotomatiki — mtu wa Zara Cars anaosimama anapokea.",
    "diaspora.subhead":
      "Mfumo wa kawaida kwa Wakenya wa nje wanunuao kwa familia nyumbani: lipa kwa USD/EUR, mawasiliano ya mtu mwingine wa Nairobi, taarifa za WhatsApp badala ya kuingia kwenye tovuti.",
    "legal.subhead":
      "Tuchapue sera ambayo mito mingi ya wafanyabiashara inaficha. Kama una swali, tuulize moja kwa moja kwa WhatsApp.",
  },
};

type TranslationContextType = {
  language: Language;
  toggle: () => void;
  t: (key: string, fallback?: string) => string;
};

const TranslationContext = createContext<TranslationContextType>({
  language: "en",
  toggle: () => {},
  t: (key, fallback) => fallback ?? key,
});

export function TranslationProvider({
  children,
}: {
  children: React.ReactNode;
}) {
  const [language, setLanguage] = useState<Language>("en");
  const toggle = () => setLanguage(prev => (prev === "en" ? "sw" : "en"));
  const t = (key: string, fallback?: string) =>
    translations[language][key] ?? fallback ?? key;
  return (
    <TranslationContext.Provider value={{ language, toggle, t }}>
      {children}
    </TranslationContext.Provider>
  );
}

export function useTranslation() {
  return useContext(TranslationContext);
}
